apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: jira-secret-display
    namespace: team-service-management
    labels:
        team: team-service-management
spec:
  ingresses:
    - https://jira-secret-display.intern.nav.no
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
      singlePageApplication: false
    sidecar:
        enabled: true
        autoLogin: true
        autoLoginIgnorePaths:
          - /health/*
