apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tsm-skjermd-frontend
    namespace: team-service-management
    labels:
        team: team-service-management
spec:
  envFrom:
    - secret: serviceaccounts-jira
    - secret: tsm-skjermd-frontend
  ingresses:
    - https://tsm-skjermd-frontend.intern.nav.no
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
      singlePageApplication: false
    sidecar:
        enabled: true
        autoLogin: true
        autoLoginIgnorePaths:
          - /health/*
          - /assets/*
          - /favicon.svg
          - /embed/api/saker/*
          - /embed/api/saker/*/tilganger
          - /embed/api/saker/*/tilganger/*
          - /embed/sensurering/*
          - /embed/sensurering-editor/*
          - /embed/api/saker/*/sensurering
          - /embed/api/saker/*/filer
          - /embed/api/saker/*/filer/*
          - /embed/api/jira/update-description
          - /embed/api/jira/add-comment
          - /api/generate-embed-token
          - /api/validate-embed-token
